### ISSUE TITLE
Put the configurator above setHandler in run-jetty function.

### ISSUE THREAD

**Issue by clyfe** [mpenet/jet#15]
And also add the hs HandlerList as an optional parameter.

**Comment by mpenet** [comment]
does the configurator setting order has an impact?

**Comment by mpenet** [comment]
The original adapter seems to use the same ordering: 
https://github.com/ring-clojure/ring/blob/master/ring-jetty-adapter/src/ring/adapter/jetty.clj#L97-L101 

I'd rather do the same, unless you can give me a good reason not to do so.

Cheers

**Comment by mpenet** [comment]
I have moved things around a bit in that file. a lot of it originates from the parent project. It should be easier to follow now and I also made the addhandler calls only happen if necesary (which is what caused you the most trouble I suppose).

**Comment by clyfe** [comment]
It would allow to add servlets via the configurator. Not sure if it breaks stuff for other people.

**Comment by mpenet** [comment]
feel free to try with the current snapshot, I really doubt the order of calls makes any difference.
