### ISSUE TITLE
Add callback for modifying Server before starting

### ISSUE THREAD

**Issue by hlship** [mpenet/jet#17]
I'm attempting (and its a bit of a leap!) to integrate New Relic monitoring into our app; I'm having to do some ugly alter-var-root stuff to hack things so that I can intercept the incoming servlet request and response.

It would be nice if an option to qbits.jet.server/run-jetty was a callback function that could tweak the Server instance before it is started.

**Comment by mpenet** [comment]
I was actually thinking about adding that. I ll see what I can do later today

**Comment by mpenet** [comment]
well you can do it already, see the `configurator` option. 

https://github.com/mpenet/jet/blob/master/src/clj/qbits/jet/server.clj#L193-L194 

This is documented nowhere tho and it's probably a left-over from the jetty-adapter copy pasta
