### ISSUE TITLE
class not found at start

### ISSUE THREAD

**Issue by sihingkk** [mpenet/jet#26]
I'm getting following error on "lein run":

Exception in thread "main" java.lang.ClassNotFoundException: qbits.jet.server, compiling:(jetty_9/core.clj:14:3)

here is the code:
https://github.com/sihingkk/clojure-jetty-9

**Comment by mpenet** [comment]
There are a few errors in your example: main should be -main, the arguments of the main function should be [& args], but more importantly you need to require the qbits.jet.server namespace.

**Comment by sihingkk** [comment]
many thanks for answer
