### ISSUE TITLE
server side reading HTTP input

### ISSUE THREAD

**Issue by nicferrier** [mpenet/jet#38]
When receving a request via an async channel, if the server has sent a request body I presume that is NOT available as a channel? 

Instead I have to read that conventionally, as I would in Java?

**Comment by mpenet** [comment]
Hi, 

It's not super clear what context you are refering to (since jet has both client/server it's a bit confusing): 

if you mean reading the :body key in a request map from the server side, yes, it's an inputstream.

**Comment by nicferrier** [comment]
That's what I meant, it's an InputStream, not a channel.

**Comment by mpenet** [comment]
We could add a server option that make the receive happen in a channel since I believe the jetty9 api can allow to control how/when (exert backpressure) we receive it. That would make sense given the current jet api.

**Comment by nicferrier** [comment]
It would. But I'll handle it with an input stream for now.
