### ISSUE TITLE
Example/Document how ring and websocket works together

### ISSUE THREAD

**Issue by hyPiRion** [mpenet/jet#44]
The documentation on how to use jet for vanilla ring and websocket handlers is fine, but it does not describe what to do if you want to support both types of handlers on the same jetty server instance (let alone whether it is possible in the first place!). I think it would be beneficial to include an example or some documentation on how one can do that (if it is possible).

**Comment by mpenet** [comment]
Right! Good catch. 

(it actually is possible, but you prolly know about it already)

**Comment by mpenet** [comment]
fixed in e839a161822def568390a481b577c9e7f7e36e9d
