### ISSUE TITLE
JSON encoding acting strange

### ISSUE THREAD

**Issue by noxecane** [mpenet/jet#45]
I am sorry for the title.

I was trying to use the http client to communicate with  the couchdb REST api. Some enpoints require JSON payload so I used the `:form-params` and `:content-type` fields to send json data but kept getting
 `invalid UTF-8 JSON`. I discovered this error is caused by lack of `\"` for strings in the json body. So I used chesire directly to put strings on`:body`. I just wanted to know if this is the correct behaviour and my hack is not based on some wrong assumption of how the lib works

**Comment by mpenet** [comment]
No worries. 
If you want to send the body as json you need to json encode the value that you pass to `:body` (with cheshire for instance). There's no automatic body encoding depending on the content-type in jet.

**Comment by mpenet** [comment]
FYI, I am planning on deprecating jet in favor of https://github.com/pyr/net.

**Comment by noxecane** [comment]
You mean the entire server...will it support websockets
