### ISSUE TITLE
increasing body chunk sizes

### ISSUE THREAD

**Issue by pyr** [mpenet/jet#7]
Hi !

When streaming data from a request's body by treating it as an `InputStream` (which `HttpInputOverHTTP` implements), the typical chunk size I am getting from reads is 8k.

I haven't found a way to modify that and would be happy with letting jetty hand over bigger chunks, ideally in a configurable manner.

Did I miss the way to do it or is it not exposed by jetty ?

Cheers!

**Comment by mpenet** [comment]
I think I have managed to find a way to have control over this via  http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/server/AbstractConnectionFactory.html#setInputBufferSize(int) . Let me know if that changes anything for you. It's available as of 0.5.10

**Comment by pyr** [comment]
Hey!

This works as expected (well, not quite, but it does increase the amount of chunks processed). If I want anything more granular, I'll have to got to netty anyway.

Thanks a lot!
